theme: jekyll-theme-primer

title: Introduction aux humanités numériques
description: Contenus pour le cours « Humanités Numériques » des L2 SDL et InfoCom de l'université Paris Nanterre 
emojicon: 📚

url: https://loicgrobol.github.io/
baseurl: /introhumnum
repository: "loicgrobol//introhumnum"

exclude:
  - renv

include:
  - _pages
