---
title: "Humanités Numériques"
subtitle: "Cours 8 : Sonder un grand corpus"
author: Loïc Grobol
date: 2021-11-09
lang: fr-FR
bibliography: "../../biblio.bib"
csl: "../association-for-computational-linguistics.csl"
output:
  revealjs::revealjs_presentation:
    css: "../reveal_slides_style.css"
    theme: white
    highlight: pygments
    reveal_options:
      slideNumber: true
      progress: true
  pdf_document:
    latex_engine: "lualatex"
---

[comment]: <> "LTeX: language=fr"

# Google Books

- Collection multilingue de livres de 1500 à 2008
- Numérisation de plus de 5 millions de livres grâce à la reconnaissance optique de caractères (OCR)
- 500 milliards de mots cf. J. Michel et al. (2011). “Quantitative Analysis of Culture Using
  Millions of Digitized Books”, Science, vol. 331
- Nombre de mots par langues :
  - anglais : 361 milliards
  - français : 45 milliards
  - espagnol : 45 milliards
  - allemand : 37 milliards

# Mots ?

Extraction des « mots » en fonction :

- des caractères blancs
- de la ponctuation, des tirets et des apostrophes

Beaucoup de bruit :

- erreurs de reconnaissance automatique
- typos
- mots qui contiennent des chiffres, abréviations, etc.
- utilisation d’autres langues dans un livre majoritairement en anglais

# Un mot ou un “gram” ?

**token** : chaîne de caractères délimitée par des espaces

- 1-gramme (ou unigramme) : 1 token
- 2-gramme (ou bigramme) : une suite de 2 tokens
- 3-gramme (ou trigramme) : une suite de 3 tokens
- n-gramme : une suite de $n$ tokens

---

Exemple : 

> Quand le mystère est trop impressionnant, on n’ose pas désobéir

- **Unigrammes** : Quand / le / mystère / est / trop / impressionnant / on / n’ose / pas / désobéir
- **Bigrammes** : Quand le / le mystère / mystère est / est trop / trop impressionnant /
  impressionnant on / on n’ose / n’ose pas / pas désobéir
- **Trigrammes** : Quand le mystère / le mystère est / mystère est trop / est trop impressionnant / trop
  impressionnant on / impressionnant on n’ose / on n’ose pas / n’ose pas désobéir

---

Exercice : compter les bigrammes dans la phrase suivante :

> Longtemps je me suis couché de bonne heure

---

1. Longtemps je
2. je me
3. me suis
4. suis couché
5. couché de
6. de bonne
7. bonne heure

# *Ngram Viewer*

Permet de faire des requêtes dans Google Books :

- n-grammes de mots
- n-grammes de catégories grammaticales (parties du discours)

Exemple : [« vélocipède » vs « vélo » vs
« bicyclette »](https://books.google.com/ngrams/graph?content=v%C3%A9locip%C3%A8de%2Cv%C3%A9lo%2Cbicyclette&year_start=1800&year_end=2019&corpus=30&smoothing=3)

→ L'évolution des fréquences relatives des n-grammes dans le corpus

## Questions d'usage

[Dit-on « autant pour moi » ou « au temps pour
moi » ?](https://books.google.com/ngrams/graph?content=autant+pour+moi%2Cau+temps+pour+moi&year_start=1800&year_end=2019&corpus=30&smoothing=3&direct_url=t1%3B%2Cautant%20pour%20moi%3B%2Cc0%3B.t1%3B%2Cau%20temps%20pour%20moi%3B%2Cc0)

---

[« par contre » ou « en
revanche »](https://books.google.com/ngrams/graph?content=par+contre%2Cen+revanche&year_start=1800&year_end=2019&corpus=30&smoothing=3&direct_url=t1%3B%2Cpar%20contre%3B%2Cc0%3B.t1%3B%2Cen%20revanche%3B%2Cc0)

---

« *the United States are* » ou « *the United States is* »

- [Anglais
  Américain](https://books.google.com/ngrams/graph?content=the+United+States+are%2Cthe+United+States+is&year_start=1800&year_end=2019&corpus=29&smoothing=3)
- [Anglais
  Britannique](https://books.google.com/ngrams/graph?content=the+United+States+are%2Cthe+United+States+is&year_start=1800&year_end=2019&corpus=28&smoothing=3)

## Évolution des nominations

[Ouvriers, travailleurs ou
salariés](https://books.google.com/ngrams/graph?content=ouvrier%2Ctravailleur%2Csalari%C3%A9%2Cemploy%C3%A9%2Ccollaborateur&year_start=1800&year_end=2019&corpus=30&smoothing=3&direct_url=t1%3B%2Couvrier%3B%2Cc0%3B.t1%3B%2Ctravailleur%3B%2Cc0%3B.t1%3B%2Csalari%C3%A9%3B%2Cc0%3B.t1%3B%2Cemploy%C3%A9%3B%2Cc0%3B.t1%3B%2Ccollaborateur%3B%2Cc0)

[Et au
pluriel](https://books.google.com/ngrams/graph?content=ouvriers%2Ctravailleurs%2Cemploy%C3%A9s%2Csalari%C3%A9s%2Ccollaborateurs&year_start=1800&year_end=2019&corpus=30&smoothing=3&direct_url=t1%3B%2Couvriers%3B%2Cc0%3B.t1%3B%2Ctravailleurs%3B%2Cc0%3B.t1%3B%2Cemploy%C3%A9s%3B%2Cc0%3B.t1%3B%2Csalari%C3%A9s%3B%2Cc0%3B.t1%3B%2Ccollaborateurs%3B%2Cc0)

---

[Féminisation des noms de
métiers](https://books.google.com/ngrams/graph?content=une+auteur%2Cune+auteure%2Cune+autrice&year_start=1800&year_end=2019&corpus=30&smoothing=3&direct_url=t1%3B%2Cune%20auteur%3B%2Cc0%3B.t1%3B%2Cune%20auteure%3B%2Cc0%3B.t1%3B%2Cune%20autrice%3B%2Cc0)

[et des
fonctions](https://books.google.com/ngrams/graph?content=%2Cmadame+la+s%C3%A9natrice%2Cmadame+le+s%C3%A9nateur&year_start=1800&year_end=2019&corpus=30&smoothing=3&direct_url=t1%3B%2Cmadame%20la%20s%C3%A9natrice%3B%2Cc0%3B.t1%3B%2Cmadame%20le%20s%C3%A9nateur%3B%2Cc0)

## Un proxy pour les LSHS

[Le
communisme](https://books.google.com/ngrams/graph?content=Marx%2CStaline%2CL%C3%A9nine%2CMao&year_start=1800&year_end=2019&corpus=30&smoothing=3&direct_url=t1%3B%2CMarx%3B%2Cc0%3B.t1%3B%2CStaline%3B%2Cc0%3B.t1%3B%2CL%C3%A9nine%3B%2Cc0%3B.t1%3B%2CMao%3B%2Cc0)

## Des trucs mécaniques

[Les années
absolues](https://books.google.com/ngrams/graph?content=2000%2C2001%2C2002%2C2003%2C2004%2C2005%2C2006&year_start=1990&year_end=2019&corpus=30&smoothing=3&direct_url=t1%3B%2C2000%3B%2Cc0%3B.t1%3B%2C2001%3B%2Cc0%3B.t1%3B%2C2002%3B%2Cc0%3B.t1%3B%2C2003%3B%2Cc0%3B.t1%3B%2C2004%3B%2Cc0%3B.t1%3B%2C2005%3B%2Cc0%3B.t1%3B%2C2006%3B%2Cc0)

[et
relatives](https://books.google.com/ngrams/graph?content=cette+ann%C3%A9e%2Cl%27ann%C3%A9e+derni%C3%A8re%2Cl%27ann%C3%A9e+prochaine&year_start=1990&year_end=2019&corpus=30&smoothing=3&direct_url=t1%3B%2Ccette%20ann%C3%A9e%3B%2Cc0%3B.t1%3B%2Cl%27%20ann%C3%A9e%20derni%C3%A8re%3B%2Cc0%3B.t1%3B%2Cl%27%20ann%C3%A9e%20prochaine%3B%2Cc0)

# Opérations

## Multiplier et diviser par un nombre

Utiliser les opérateurs `*` et `/` :

[`ouvrier,travailleur,(prolétaire*10)`](https://books.google.com/ngrams/graph?content=cette+ann%C3%A9e%2Cl%27ann%C3%A9e+derni%C3%A8re%2Cl%27ann%C3%A9e+prochaine&year_start=1990&year_end=2019&corpus=30&smoothing=3&direct_url=t1%3B%2Ccette%20ann%C3%A9e%3B%2Cc0%3B.t1%3B%2Cl%27%20ann%C3%A9e%20derni%C3%A8re%3B%2Cc0%3B.t1%3B%2Cl%27%20ann%C3%A9e%20prochaine%3B%2Cc0)

[`(ouvrier/10),(travailleur/10),prolétaire`](https://books.google.com/ngrams/graph?content=%28ouvrier%2F10%29%2C%28travailleur%2F10%29%2Cprol%C3%A9taire&year_start=1800&year_end=2019&corpus=30&smoothing=3&direct_url=t1%3B%2C%28ouvrier%20/%2010%29%3B%2Cc0%3B.t1%3B%2C%28travailleur%20/%2010%29%3B%2Cc0%3B.t1%3B%2Cprol%C3%A9taire%3B%2Cc0)

Parenthèses obligatoires !

## Additionner et soustraire

Sans surprise avec `+` et `-` :

[`(United States is-United States are)`](https://books.google.com/ngrams/graph?content=%28United+States+is-United+States+are%29&year_start=1800&year_end=2019&corpus=28&smoothing=3&direct_url=t1%3B%2C%28United%20States%20is%20-%20United%20States%20are%29%3B%2Cc0)

[`(Bigfoot+Sasquatch),Yeti](https://books.google.com/ngrams/graph?content=%28Bigfoot%2BSasquatch%29%2CYeti&year_start=1800&year_end=2019&corpus=28&smoothing=3&direct_url=t1%3B%2C%28Bigfoot%20%2B%20Sasquatch%29%3B%2Cc0%3B.t1%3B%2CYeti%3B%2Cc0)

## Catégories grammaticales

Avec `_{CATEGORIE}`, par exemple `salarié_NOUN`

[`ouvrier,salarié_NOUN,travailleur_NOUN,employé_NOUN`](https://books.google.com/ngrams/graph?content=ouvrier%2Csalari%C3%A9_NOUN%2Ctravailleur_NOUN%2Cemploy%C3%A9_NOUN&year_start=1800&year_end=2019&corpus=30&smoothing=3&direct_url=t1%3B%2Couvrier%3B%2Cc0%3B.t1%3B%2Csalari%C3%A9_NOUN%3B%2Cc0%3B.t1%3B%2Ctravailleur_NOUN%3B%2Cc0%3B.t1%3B%2Cemploy%C3%A9_NOUN%3B%2Cc0)

---

| Code   | Catégorie   |
| ------ | ----------- |
| _NOUN_ | nom         |
| _VERB_ | verbe       |
| _ADJ_  | adjectif    |
| _ADV_  | adverbe     |
| _PRON_ | pronom      |
| _DET_  | déterminant |
| _ADP_  | adposition  |
| _NUM_  | chiffre     |
| _CONJ_ | conjonction |
| _PRT_  | particule   |

Pour les linguistes : c'est un sous-ensemble des [*Universal Part of
Speech*](https://universaldependencies.org/u/pos).

# Le joker

Un autre usage de `*` : remplacer n'import quel mot.

Exemple : [`une colère
*`](https://books.google.com/ngrams/graph?content=une+col%C3%A8re+%2A&year_start=1800&year_end=2019&corpus=30&smoothing=3&direct_url=t2%3B%2Cune%20col%C3%A8re%20%2A%3B%2Cc0%3B%2Cs0%3B%3Bune%20col%C3%A8re%20qui%3B%2Cc0%3B%3Bune%20col%C3%A8re%20noire%3B%2Cc0%3B%3Bune%20col%C3%A8re%20terrible%3B%2Cc0%3B%3Bune%20col%C3%A8re%20de%3B%2Cc0%3B%3Bune%20col%C3%A8re%20%C3%A9pouvantable%3B%2Cc0%3B%3Bune%20col%C3%A8re%20sourde%3B%2Cc0%3B%3Bune%20col%C3%A8re%20violente%3B%2Cc0%3B%3Bune%20col%C3%A8re%20froide%3B%2Cc0%3B%3Bune%20col%C3%A8re%20et%3B%2Cc0%3B%3Bune%20col%C3%A8re%20concentr%C3%A9e%3B%2Cc0)
donne les fréquences de trigrammes dont les deux premiers mots sont « une » et « colère »

# Les dépendances syntaxiques

`y => x` permet de savoir à quelle fréquence un mot x (« tigré », « roux » ou « noir ») modifie un
mot y (« chat »)

[`chat=>noir,chat=>roux,chat=>tigré`](https://books.google.com/ngrams/graph?content=chat+%3D%3E+noir%2C+chat+%3D%3E+roux%2C+chat+%3D%3E+tigr%C3%A9&year_start=1800&year_end=2019&corpus=30&smoothing=3&direct_url=t1%3B%2Cchat%3D%3Enoir%3B%2Cc0%3B.t1%3B%2Cchat%3D%3Eroux%3B%2Cc0%3B.t1%3B%2Cchat%3D%3Etigr%C3%A9%3B%2Cc0#t1%3B%2Cchat%3D%3Enoir%3B%2Cc0%3B.t1%3B%2Cchat%3D%3Eroux%3B%2Cc0%3B.t1%3B%2Cchat%3D%3Etigr%C3%A9%3B%2Cc0)

Le concept de dépendance syntaxique est en fait plus vaste que ça : regardez par exemple
[`parle=>je,je parle,je *
parle`](https://books.google.com/ngrams/graph?content=parle%3D%3Eje%2Cje+parle%2Cje+%2A+parle&year_start=1800&year_end=2019&corpus=30&smoothing=3&direct_url=t1%3B%2Cparle%3D%3Eje%3B%2Cc0%3B.t1%3B%2Cje%20parle%3B%2Cc0%3B.t2%3B%2Cje%20%2A%20parle%3B%2Cc0%3B%2Cs0%3B%3Bje%20ne%20parle%3B%2Cc0%3B%3Bje%20vous%20parle%3B%2Cc0%3B%3Bje%20te%20parle%3B%2Cc0%3B%3Bje%20lui%20parle%3B%2Cc0%3B%3Bje%20n%27en%20parle%3B%2Cc0%3B%3Bje%20leur%20parle%3B%2Cc0%3B%3Bje%20t%27en%20parle%3B%2Cc0%3B%3Bje%20me%20parle%3B%2Cc0%3B%3Bje%20le%20parle%3B%2Cc0%3B%3Bje%20n%27y%20parle%3B%2Cc0).

# Autres fonctionnalités

Voir [la doc](https://books.google.com/ngrams/info)

- `_INF` : formes fléchies d’un verbe »> ex :
[`manger_INF`](https://books.google.com/ngrams/graph?content=manger_INF&year_start=1800&year_end=2019&corpus=30&smoothing=3&direct_url=t3%3B%2Cmanger_INF%3B%2Cc0%3B%2Cs0%3B%3Bmanger%3B%2Cc0%3B%3Bmange%3B%2Cc0%3B%3Bmang%C3%A9%3B%2Cc0%3B%3Bmangent%3B%2Cc0%3B%3Bmangeait%3B%2Cc0%3B%3Bmangeant%3B%2Cc0%3B%3Bmangeaient%3B%2Cc0%3B%3Bmangea%3B%2Cc0%3B%3Bmangez%3B%2Cc0%3B%3Bmang%C3%A9s%3B%2Cc0%3B%3Bmang%C3%A9e%3B%2Cc0%3B%3Bmang%C3%A8rent%3B%2Cc0%3B%3Bmangeons%3B%2Cc0%3B%3Bmangera%3B%2Cc0%3B%3Bmang%C3%A9es%3B%2Cc0%3B%3Bmangeront%3B%2Cc0%3B%3Bmanges%3B%2Cc0%3B%3Bmangerez%3B%2Cc0%3B%3Bmangeais%3B%2Cc0%3B%3Bmangerai%3B%2Cc0%3B%3Bmangions%3B%2Cc0%3B%3Bmangerait%3B%2Cc0%3B%3Bmangeras%3B%2Cc0%3B%3Bmangerons%3B%2Cc0%3B%3Bmangeai%3B%2Cc0%3B%3Bmange%C3%A2mes%3B%2Cc0%3B%3Bmangeraient%3B%2Cc0%3B%3Bmangerais%3B%2Cc0%3B%3Bmange%C3%A2t%3B%2Cc0%3B%3Bmangiez%3B%2Cc0%3B%3Bmangeassent%3B%2Cc0%3B%3Bmangers%3B%2Cc0%3B%3Bmangerions%3B%2Cc0%3B%3Bmangeriez%3B%2Cc0%3B%3Bmangeasse%3B%2Cc0%3B%3Bmangeas%3B%2Cc0%3B%3Bmange%C3%A2tes%3B%2Cc0%3B%3Bmangeassions%3B%2Cc0%3B%3Bmangeassiez%3B%2Cc0%3B%3Bmangeasses%3B%2Cc0)
- `*` avant une catégorie grammaticale : remplace n’importe quel mot de cette catégorie
- [`*_ADJ`](https://books.google.com/ngrams/graph?content=%2A_ADJ&year_start=1800&year_end=2019&corpus=30&smoothing=3&direct_url=t2%3B%2C%2A_ADJ%3B%2Cc0%3B%2Cs0%3B%3Bd%27_ADJ%3B%2Cc0%3B%3Bm%C3%AAme_ADJ%3B%2Cc0%3B%3Btous_ADJ%3B%2Cc0%3B%3Bautre_ADJ%3B%2Cc0%3B%3Bautres_ADJ%3B%2Cc0%3B%3Bdeux_ADJ%3B%2Cc0%3B%3Btoutes_ADJ%3B%2Cc0%3B%3Bgrand_ADJ%3B%2Cc0%3B%3Bgrande_ADJ%3B%2Cc0%3B%3Bpremier_ADJ%3B%2Cc0)
    renvoie n’importe quel adjectif (les 10 plus fréquents sont renvoyés)
- `_START_` : début de la phrase
- `_END_` : fin de la phrase
- `_ROOT_` : racine de l’arbre de dépendance de la phrase

# À vous de jouer !

[Faire la fiche d'exercices](exos-08.html)

<!-- # Bibliographie

::: {#refs}
::: -->

# Remerciements

Pour les versions précédentes de ce cours que nous avons construit au fil des années, merci à
Isabelle Tellier, Kim Gerdes, Serge Fleury, Yoann Dupont, Pablo Ruiz Fabo, Marine Delaborde et
Mathilde Regnault.