---
title: "Humanités Numériques"
subtitle: "Cours 7 : Les bibliothèques numériques"
author: Loïc Grobol
date: 2021-10-19
lang: fr-FR
bibliography: "../../biblio.bib"
csl: "../association-for-computational-linguistics.csl"
output:
  revealjs::revealjs_presentation:
    css: "../reveal_slides_style.css"
    theme: white
    highlight: pygments
    reveal_options:
      slideNumber: true
      progress: true
  pdf_document:
    latex_engine: "lualatex"
---

[comment]: <> "LTeX: language=fr"

# Les bibliothèques numériques

- Années 1970 : l’informatique : numériser les ouvrages
- Années 1980 : Numérisation patrimoniale
- Apparition d’Internet : Développement des Bibliothèques en ligne

---

> Un ensemble de ressources numériques et technologies associées pour créer, repérer et utiliser
> l’information ; les bibliothèques incluent des données, métadonnées et liens (métadonnées) vers
> d’autres ressources  
> [@dasylva2013GeneseDescriptionBibliotheques]

---

Quels points communs avec les bibliothèques historiques ? Quelles différences ?

# Projets

## Grandes bibliothèques publiques

- [Gallica](http://gallica.bnf.fr/), bibliothèque numérique de la BnF
- [*Online Gallery*](http://www.bl.uk/onlinegallery), de la *British Library*
- [*American Memory*](http://memory.loc.gov/ammem/index.html), de la *Library of Congress*
- [*Trove*](http://trove.nla.gov.au/), de la *National Library of Australia*

## Grands projets internationaux publics

- [*Europeana*](http://www.europeana.eu), la bibliothèque numérique européenne
- [*World Digital Library*](http://www.wdl.org/fr/), bibliothèque numérique
mondiale

## Grands projets de numérisation privés et associatifs

- [Projet Gutenberg](http://www.gutenberg.org)
- [Wikisource](http://fr.wikisource.org) et [Wikimedia Commons](https://commons.wikimedia.org)
- [Internet Archive](http://www.archive.org)
- [Google Livres](http://books.google.fr)

## Projets clandestins

- [*Z library*](https://z-lib.org/)
- [*Library Genesis*](libgen.is)


# Bibliographie

::: {#refs}
:::
