# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on: [push, pull_request]

name: CI-CD

jobs:
  CI-CD:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      # we keep a matrix for convenience, but we would always want to run on one
      # single OS and R version
      matrix:
        config:
          - {os: ubuntu-20.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install dependencies
        run: |
          install.packages(c("rmarkdown", "revealjs"))
        shell: Rscript {0}

      - name: Create the build dir
        run: |
          mkdir _build
      - name: Build site
        run: |
          rmarkdown::render('slides/lecture-01/lecture-01.Rmd',output_file='_build/lecture-01.html')
        shell: Rscript {0}

      - name: Upload built site artifact
        uses: actions/upload-artifact@v1
        with:
          name: site
          path: _build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          target_branch: gh-pages
          build_dir: _build
          jekyll: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}